let localdata = [
    {
      ga_gender: "female",
      Organization: "pepsico",
      create_date: "3/25/14 8:58",
      conference_code: "ACMP18",
      primary: "alert",
      secondary: "passion",
      dormant: "mystique",
      archetype: "The Coordinator",
      user_id: "747298",
      power: "8",
      trust: "12",
      prestige: "11",
      passion: "13",
      mystique: "8",
      innovation: "9",
      alert: "16"
    },
    {
      ga_gender: "female",
      Organization: "cbrands",
      create_date: "3/25/14 8:57",
      conference_code: "ACMP18",
      primary: "passion",
      secondary: "alert",
        dormant: "innovation",
        archetype: "The Orchestrator",
        user_id: "747297",
        power: "9",
        trust: "10",
        prestige: "11",
        passion: "12",
        mystique: "11",
        innovation: "9",
        alert: "12"
    },
    {
      ga_gender: "male",
      Organization: "bmrn",
      create_date: "3/25/14 8:52",
      conference_code: "ACMP18",
      primary: "trust",
      secondary: "prestige",
      dormant: "alert",
      archetype: "The Diplomat",
      user_id: "747294",
      power: "9",
      trust: "11",
      prestige: "11",
      passion: "10",
      mystique: "10",
      innovation: "10",
      alert: "9"
    }
  ]